package com.example.accessingdatamysql;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;


@Controller	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
        
        @Autowired // This means to get the bean called eventRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
        private EventRepository eventRepository;

	@PostMapping(path="/create") // Map ONLY POST Requests
	public String CreateNewUser (@RequestParam String username
			, @RequestParam String email, @RequestParam Integer eventID) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request
            User n = new User();
            n.setName(username);
            n.setEmail(email);
            System.out.println();
            List<Event> events = (List<Event>) eventRepository.findAll();
            Event event = null;
            for(int i = 0; i < events.size(); i++){
                if(events.get(i).getId().equals(eventID)){
                    event = events.get(i);
                } else {
                }
            }
            if(event == null){
                return "redirect:all_event?message=ERROR : No event found";
            }
            n.addEvent(event);
            event.addUser(n);
            userRepository.save(n);
            return "redirect:all_user";
	}
        
        
        @PostMapping(path="/add") // Map ONLY POST Requests
	public String addNewUser (@RequestParam Integer userID
			, @RequestParam Integer eventID) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request
            List<User> users = (List<User>) userRepository.findAll();   
            User user = null;
            for(int i = 0; i < users.size(); i++){
                if(users.get(i).getId().equals(userID)){
                    user = users.get(i);
                } else {
                }
            }
            if(user == null){
                return "redirect:all_user?message=ERROR : No user found";
            }
            
            List<Event> events = (List<Event>) eventRepository.findAll();  
            Event event = null;
            for(int i = 0; i < events.size(); i++){
                if(events.get(i).getId().equals(eventID)){
                    event = events.get(i);
                } else {
                }
            }
            if(event == null){
                return "redirect:all_event?message=ERROR : No event found";
            }
            
            if(!event.getUsers().contains(user) && !user.getEvents().contains(event)){
                event.addUser(user);
                user.addEvent(event);
                eventRepository.save(event);
                return "redirect:all_user";
            }
            else{
                return "redirect:all_user?message=ERROR : user already added";
            }
	}
        

	@GetMapping(path="/all_user")
	public String getAllUsers(Model model, @RequestParam(name="message", required=false, defaultValue="") String message) {
            // This returns a JSON or XML with the users
            Iterable<User> json = userRepository.findAll();
            model.addAttribute("json", json);
            model.addAttribute("message", message);
            return "all_user";
	}
                
        @PostMapping(path="/delete_user") // Map ONLY POST Requests
	public String deleteUser (@RequestParam Integer userID) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request
            List<User> users = (List<User>) userRepository.findAll();   
            User user = null;
            for(int i = 0; i < users.size(); i++){
                if(users.get(i).getId().equals(userID)){
                    user = users.get(i);
                } else {
                }
            }
            if(user == null){
                return "redirect:all_user?message=ERROR : No user found";
            }
            user.clearEvents();
            userRepository.delete(user);
            return "redirect:all_user";
	}
        
        @GetMapping("/register/user")
	public String greeting(Model model) {
            Iterable<Event> events = eventRepository.findAll();
            Iterable<User> users = userRepository.findAll();
            model.addAttribute("users", users);
            model.addAttribute("events", events);
            return "user";
	}
}
